In [172]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

pd.set_option("display.max_columns", None)

In [173]:
df = pd.read_csv(
    "alloy_data.csv", sep=';',  # correct delimiter
    encoding='utf-8-sig'  # removes BOM issue
)

In [174]:
print(df.columns.tolist())

df.columns = df.columns.str.replace('\ufeff', '', regex=True)

['\ufeffproperty_id', 'id', 'full_address', 'street_address', 'unit', 'city', 'state', 'zip_code', 'county', 'latitude', 'longitude', 'property_type', 'bedrooms', 'bathrooms', 'sqft', 'lot_size_sqft', 'year_built', 'building_age', 'last_sale_price', 'last_sale_date', 'days_since_sale', 'price_per_sqft', 'assessed_value', 'tax_year', 'annual_tax', 'owner_name', 'owner_occupied', 'assessor_id']

In [175]:
print(df.shape)
print(df.columns)
df.head()

(2090, 28)
Index(['property_id', 'id', 'full_address', 'street_address', 'unit', 'city',
       'state', 'zip_code', 'county', 'latitude', 'longitude', 'property_type',
       'bedrooms', 'bathrooms', 'sqft', 'lot_size_sqft', 'year_built',
       'building_age', 'last_sale_price', 'last_sale_date', 'days_since_sale',
       'price_per_sqft', 'assessed_value', 'tax_year', 'annual_tax',
       'owner_name', 'owner_occupied', 'assessor_id'],
      dtype='str')

,property_id,id,full_address,street_address,unit,city,state,zip_code,county,latitude,longitude,property_type,bedrooms,bathrooms,sqft,lot_size_sqft,year_built,building_age,last_sale_price,last_sale_date,days_since_sale,price_per_sqft,assessed_value,tax_year,annual_tax,owner_name,owner_occupied,assessor_id
0,P-100001,10001,"1924 Oak Ave, Honolulu, HI 46048",1924 Oak Ave,NaN,Honolulu,HI,46048,Honolulu,27.489634,-144.860200,Single Family,6,5.0,"1,312","10,986",1974,50,"546,937.17",2025-03-26,384,416.87,"473,424.11",2024,"7,207.52",Emily Gonzalez,False,HI-HO-81426
1,P-100002,10002,"3711 Harbor View Blvd, Pittsburgh, PA 87236",3711 Harbor View Blvd,NaN,Pittsburgh,PA,87236,Allegheny,28.372054,-81.370872,Single Family,6,4.0,"3,387","7,939",1939,85,"287,944.73",2017-09-20,"3,128",85.01,"259,431.97",2022,"3,258.24",Matthew Thompson,False,PA-AL-15695
2,P-100003,10003,"8885 Park Way, Apt 21C, Kansas City, MO 59615",8885 Park Way,Apt 21C,Kansas City,MO,59615,Jackson,23.088205,-131.493490,Townhouse,7,3.5,"5,329","8,479",2010,14,"174,253.02",2018-11-13,"2,709",32.70,"151,316.00",2023,"2,999.49",Joseph Miller,True,MO-JA-69429
3,P-100004,10004,"6165 Hillcrest Ave, Bronx, NY 37460",6165 Hillcrest Ave,NaN,Bronx,NY,37460,Bronx,38.759642,-95.941633,Single Family,5,2.0,"4,975","16,921",1951,73,"948,377.61",2022-01-10,"1,555",190.63,"835,505.83",2024,"18,381.13",Joseph Baker,True,NY-BR-17331
4,P-100005,10005,"625 Ridgewood Rd, Apt 14E, Tucson, AZ 62581",625 Ridgewood Rd,Apt 14E,Tucson,AZ,62581,Pima,28.095133,-138.644493,Townhouse,6,3.5,"2,341","13,079",1983,41,"428,592.88",2019-01-27,"2,634",183.08,"401,872.50",2023,"3,888.34",Deborah Scott,True,AZ-PI-86622

In [195]:
# df[['property_type', 'city', 'state', 'building_age']].nunique()
df[['property_type', 'city', 'state', 'building_age']].nunique()
# print(df.columns)
# df.nunique()

property_type      4
city              84
state             33
building_age     104
dtype: int64

In [177]:
df.nunique()

property_id        2090
id                 2090
full_address       2090
street_address     2084
unit                150
city                 84
state                33
zip_code           2064
county               80
latitude           2090
longitude          2090
property_type         4
bedrooms              7
bathrooms             9
sqft               1773
lot_size_sqft      1952
year_built          104
building_age        104
last_sale_price    2090
last_sale_date     1606
days_since_sale    1606
price_per_sqft     2044
assessed_value     2090
tax_year              3
annual_tax         2089
owner_name         1450
owner_occupied        2
assessor_id        2090
dtype: int64

In [178]:
df["property_type"].value_counts()

property_type
Single Family    829
Condo            624
Townhouse        428
Multi Family     209
Name: count, dtype: int64

In [179]:
# df.groupby(df["property_type"] == "Single Family")["unit"].apply(
#     lambda x: (x == "N/A").sum()
# )

df.groupby("property_type")["unit"].agg([
    lambda x: x.isnull().sum(),          # real missing
    lambda x: (x == "N/A").sum(),        # not applicable
    lambda x: (x == "Unknown").sum()     # unknown
])

               <lambda_0>  <lambda_1>  <lambda_2>
property_type
Condo                   0           0           0
Multi Family          209           0           0
Single Family         829           0           0
Townhouse               0           0           0

In [180]:
df[df["property_type"] == "Multi Family"]["unit"].head()

27    NaN
37    NaN
41    NaN
45    NaN
49    NaN
Name: unit, dtype: str

In [181]:
df.columns = df.columns.str.strip().str.replace('"', '')

In [182]:
df = df.replace(r'\t', '', regex=True)
df = df.replace(r'\s+', ' ', regex=True)

In [183]:
df.drop_duplicates()

,property_id,id,full_address,street_address,unit,city,state,zip_code,county,latitude,longitude,property_type,bedrooms,bathrooms,sqft,lot_size_sqft,year_built,building_age,last_sale_price,last_sale_date,days_since_sale,price_per_sqft,assessed_value,tax_year,annual_tax,owner_name,owner_occupied,assessor_id
0,P-100001,10001,"1924 Oak Ave, Honolulu, HI 46048",1924 Oak Ave,NaN,Honolulu,HI,46048,Honolulu,27.489634,-144.860200,Single Family,6,5.0,"1,312","10,986",1974,50,"546,937.17",2025-03-26,384,416.87,"473,424.11",2024,"7,207.52",Emily Gonzalez,False,HI-HO-81426
1,P-100002,10002,"3711 Harbor View Blvd, Pittsburgh, PA 87236",3711 Harbor View Blvd,NaN,Pittsburgh,PA,87236,Allegheny,28.372054,-81.370872,Single Family,6,4.0,"3,387","7,939",1939,85,"287,944.73",2017-09-20,"3,128",85.01,"259,431.97",2022,"3,258.24",Matthew Thompson,False,PA-AL-15695
2,P-100003,10003,"8885 Park Way, Apt 21C, Kansas City, MO 59615",8885 Park Way,Apt 21C,Kansas City,MO,59615,Jackson,23.088205,-131.493490,Townhouse,7,3.5,"5,329","8,479",2010,14,"174,253.02",2018-11-13,"2,709",32.70,"151,316.00",2023,"2,999.49",Joseph Miller,True,MO-JA-69429
3,P-100004,10004,"6165 Hillcrest Ave, Bronx, NY 37460",6165 Hillcrest Ave,NaN,Bronx,NY,37460,Bronx,38.759642,-95.941633,Single Family,5,2.0,"4,975","16,921",1951,73,"948,377.61",2022-01-10,"1,555",190.63,"835,505.83",2024,"18,381.13",Joseph Baker,True,NY-BR-17331
4,P-100005,10005,"625 Ridgewood Rd, Apt 14E, Tucson, AZ 62581",625 Ridgewood Rd,Apt 14E,Tucson,AZ,62581,Pima,28.095133,-138.644493,Townhouse,6,3.5,"2,341","13,079",1983,41,"428,592.88",2019-01-27,"2,634",183.08,"401,872.50",2023,"3,888.34",Deborah Scott,True,AZ-PI-86622
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2085,P-102222,12222,"4671 Lake Dr, Aurora, CO 91806",4671 Lake Dr,NaN,Aurora,CO,91806,Arapahoe,46.782435,-134.329810,Single Family,6,4.0,"4,644","14,952",1922,102,"936,041.76",2025-08-08,249,201.56,"945,395.92",2022,"8,298.28",Linda Anderson,True,CO-AR-77082
2086,P-102223,12223,"2996 Willow Way, Pittsburgh, PA 76826",2996 Willow Way,NaN,Pittsburgh,PA,76826,Allegheny,27.679761,-103.284125,Single Family,1,3.0,"1,771","5,945",1928,96,"440,564.84",2019-12-19,"2,308",248.77,"440,382.07",2022,"5,081.02",James Lewis,False,PA-AL-96437
2087,P-102224,12224,"1387 Harbor View Blvd, Salt Lake City, UT 95639",1387 Harbor View Blvd,NaN,Salt Lake City,UT,95639,Salt Lake,21.281156,-119.661891,Single Family,3,2.5,"4,089","9,986",1993,31,"488,478.08",2018-10-01,"2,752",119.46,"527,344.20",2024,"8,953.70",Ashley Sanchez,True,UT-SA-23732
2088,P-102225,12225,"5226 Adams St, Apt 1D, San Diego, CA 25925",5226 Adams St,Apt 1D,San Diego,CA,25925,San Diego,43.936983,-88.841751,Townhouse,1,1.0,"4,649","11,733",1921,103,"694,999.90",2016-12-15,"3,407",149.49,"737,542.92",2023,"12,607.02",Linda Rivera,False,CA-SA-10782
2089,P-102226,12226,"9170 Adams St, Apt 24B, Rockville, MD 33464",9170 Adams St,Apt 24B,Rockville,MD,33464,Montgomery,34.432950,-72.269078,Townhouse,4,4.0,"1,440","10,114",2000,24,"813,473.07",2020-11-11,"1,980",564.91,"768,460.02",2022,"10,144.92",Dorothy Rodriguez,False,MD-MO-89182

In [184]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2090 entries, 0 to 2089
Data columns (total 28 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_id      2090 non-null   str
 1   id               2090 non-null   int64
 2   full_address     2090 non-null   str
 3   street_address   2090 non-null   str
 4   unit             1052 non-null   str
 5   city             2090 non-null   str
 6   state            2090 non-null   str
 7   zip_code         2090 non-null   int64
 8   county           2090 non-null   str
 9   latitude         2090 non-null   float64
 10  longitude        2090 non-null   float64
 11  property_type    2090 non-null   str
 12  bedrooms         2090 non-null   int64
 13  bathrooms        2090 non-null   float64
 14  sqft             2090 non-null   str
 15  lot_size_sqft    2090 non-null   str
 16  year_built       2090 non-null   int64
 17  building_age     2090 non-null   int64
 18  last_sale_price  2090 non-null   str
 19  last_sale_date   2090 non-null   str
 20  days_since_sale  2090 non-null   str
 21  price_per_sqft   2090 non-null   float64
 22  assessed_value   2090 non-null   str
 23  tax_year         2090 non-null   int64
 24  annual_tax       2090 non-null   str
 25  owner_name       2090 non-null   str
 26  owner_occupied   2090 non-null   bool
 27  assessor_id      2090 non-null   str
dtypes: bool(1), float64(4), int64(6), str(17)
memory usage: 443.0 KB

In [185]:
numeric_cols = [
    "sqft", "lot_size_sqft", "last_sale_price",
    "days_since_sale", "assessed_value", "annual_tax"
]

In [107]:
for col in numeric_cols:
    df[col] = (
        df[col]
        .astype(str)
        .str.replace(r'[^\d.]', '', regex=True)  # remove junk
    )
    df[col] = pd.to_numeric(df[col], errors='coerce')

In [108]:
df["bedrooms"] = pd.to_numeric(df["bedrooms"], errors='coerce')
df["bathrooms"] = pd.to_numeric(df["bathrooms"], errors='coerce')

df["latitude"] = pd.to_numeric(df["latitude"], errors='coerce')
df["longitude"] = pd.to_numeric(df["longitude"], errors='coerce')

df["last_sale_date"] = pd.to_datetime(df["last_sale_date"], errors='coerce')

In [186]:
# For feature_engineering.py,
# Ask chatgtp to explain why property_type(values) should not be treated the same?
# df["property_type"].value_counts()

In [155]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2090 entries, 0 to 2089
Data columns (total 28 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_id      2090 non-null   str
 1   id               2090 non-null   int64
 2   full_address     2090 non-null   str
 3   street_address   2090 non-null   str
 4   unit             2090 non-null   str
 5   city             2090 non-null   str
 6   state            2090 non-null   str
 7   zip_code         2090 non-null   int64
 8   county           2090 non-null   str
 9   latitude         2090 non-null   float64
 10  longitude        2090 non-null   float64
 11  property_type    2090 non-null   str
 12  bedrooms         2090 non-null   int64
 13  bathrooms        2090 non-null   float64
 14  sqft             2090 non-null   int64
 15  lot_size_sqft    2090 non-null   int64
 16  year_built       2090 non-null   int64
 17  building_age     2090 non-null   int64
 18  last_sale_price  2090 non-null   float64
 19  last_sale_date   2090 non-null   datetime64[us]
 20  days_since_sale  2090 non-null   int64
 21  price_per_sqft   2090 non-null   float64
 22  assessed_value   2090 non-null   float64
 23  tax_year         2090 non-null   int64
 24  annual_tax       2090 non-null   float64
 25  owner_name       2090 non-null   str
 26  owner_occupied   2090 non-null   bool
 27  assessor_id      2090 non-null   str
dtypes: bool(1), datetime64[us](1), float64(7), int64(9), str(10)
memory usage: 443.0 KB

In [110]:
df.isnull().sum()

property_id           0
id                    0
full_address          0
street_address        0
unit               1038
city                  0
state                 0
zip_code              0
county                0
latitude              0
longitude             0
property_type         0
bedrooms              0
bathrooms             0
sqft                  0
lot_size_sqft         0
year_built            0
building_age          0
last_sale_price       0
last_sale_date        0
days_since_sale       0
price_per_sqft        0
assessed_value        0
tax_year              0
annual_tax            0
owner_name            0
owner_occupied        0
assessor_id           0
dtype: int64

In [111]:
df.loc[df["property_type"] == "Single Family", "unit"] = "N/A"
df["unit"] = df["unit"].fillna("Unknown")

In [112]:
df

,property_id,id,full_address,street_address,unit,city,state,zip_code,county,latitude,longitude,property_type,bedrooms,bathrooms,sqft,lot_size_sqft,year_built,building_age,last_sale_price,last_sale_date,days_since_sale,price_per_sqft,assessed_value,tax_year,annual_tax,owner_name,owner_occupied,assessor_id
0,P-100001,10001,"1924 Oak Ave, Honolulu, HI 46048",1924 Oak Ave,N/A,Honolulu,HI,46048,Honolulu,27.489634,-144.860200,Single Family,6,5.0,1312,10986,1974,50,546937.17,2025-03-26,384,416.87,473424.11,2024,7207.52,Emily Gonzalez,False,HI-HO-81426
1,P-100002,10002,"3711 Harbor View Blvd, Pittsburgh, PA 87236",3711 Harbor View Blvd,N/A,Pittsburgh,PA,87236,Allegheny,28.372054,-81.370872,Single Family,6,4.0,3387,7939,1939,85,287944.73,2017-09-20,3128,85.01,259431.97,2022,3258.24,Matthew Thompson,False,PA-AL-15695
2,P-100003,10003,"8885 Park Way, Apt 21C, Kansas City, MO 59615",8885 Park Way,Apt 21C,Kansas City,MO,59615,Jackson,23.088205,-131.493490,Townhouse,7,3.5,5329,8479,2010,14,174253.02,2018-11-13,2709,32.70,151316.00,2023,2999.49,Joseph Miller,True,MO-JA-69429
3,P-100004,10004,"6165 Hillcrest Ave, Bronx, NY 37460",6165 Hillcrest Ave,N/A,Bronx,NY,37460,Bronx,38.759642,-95.941633,Single Family,5,2.0,4975,16921,1951,73,948377.61,2022-01-10,1555,190.63,835505.83,2024,18381.13,Joseph Baker,True,NY-BR-17331
4,P-100005,10005,"625 Ridgewood Rd, Apt 14E, Tucson, AZ 62581",625 Ridgewood Rd,Apt 14E,Tucson,AZ,62581,Pima,28.095133,-138.644493,Townhouse,6,3.5,2341,13079,1983,41,428592.88,2019-01-27,2634,183.08,401872.50,2023,3888.34,Deborah Scott,True,AZ-PI-86622
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2085,P-102222,12222,"4671 Lake Dr, Aurora, CO 91806",4671 Lake Dr,N/A,Aurora,CO,91806,Arapahoe,46.782435,-134.329810,Single Family,6,4.0,4644,14952,1922,102,936041.76,2025-08-08,249,201.56,945395.92,2022,8298.28,Linda Anderson,True,CO-AR-77082
2086,P-102223,12223,"2996 Willow Way, Pittsburgh, PA 76826",2996 Willow Way,N/A,Pittsburgh,PA,76826,Allegheny,27.679761,-103.284125,Single Family,1,3.0,1771,5945,1928,96,440564.84,2019-12-19,2308,248.77,440382.07,2022,5081.02,James Lewis,False,PA-AL-96437
2087,P-102224,12224,"1387 Harbor View Blvd, Salt Lake City, UT 95639",1387 Harbor View Blvd,N/A,Salt Lake City,UT,95639,Salt Lake,21.281156,-119.661891,Single Family,3,2.5,4089,9986,1993,31,488478.08,2018-10-01,2752,119.46,527344.20,2024,8953.70,Ashley Sanchez,True,UT-SA-23732
2088,P-102225,12225,"5226 Adams St, Apt 1D, San Diego, CA 25925",5226 Adams St,Apt 1D,San Diego,CA,25925,San Diego,43.936983,-88.841751,Townhouse,1,1.0,4649,11733,1921,103,694999.90,2016-12-15,3407,149.49,737542.92,2023,12607.02,Linda Rivera,False,CA-SA-10782
2089,P-102226,12226,"9170 Adams St, Apt 24B, Rockville, MD 33464",9170 Adams St,Apt 24B,Rockville,MD,33464,Montgomery,34.432950,-72.269078,Townhouse,4,4.0,1440,10114,2000,24,813473.07,2020-11-11,1980,564.91,768460.02,2022,10144.92,Dorothy Rodriguez,False,MD-MO-89182

In [ ]:
# df.groupby("property_type")["owner_occupied"].apply(lambda x: x.isnull().sum())

property_type
Condo            624
Multi Family     209
Single Family    829
Townhouse        428
Name: owner_occupied, dtype: int64